# Generated by Django 3.0.3 on 2020-02-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_auto_20200220_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_mobile',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
