# Generated by Django 3.0.3 on 2020-02-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_customuser_full_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_mobile',
        ),
        migrations.AddField(
            model_name='customuser',
            name='operators',
            field=models.CharField(blank=True, choices=[('050', '050'), ('051', '051'), ('055', '055'), ('070', '070'), ('077', '077'), ('099', '099')], max_length=3, null=True),
        ),
    ]
