# Generated by Django 3.0.3 on 2020-02-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_auto_20200222_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
