# Generated by Django 3.0.3 on 2020-02-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_auto_20200222_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='operators',
        ),
    ]
