# Generated by Django 3.0.3 on 2020-02-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_auto_20200222_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_link', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
