# Generated by Django 3.0.3 on 2020-02-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_auto_20200225_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserregistration',
            name='shop_link',
            field=models.URLField(blank=True, default=0, max_length=255),
        ),
    ]
