# Generated by Django 3.0.3 on 2020-02-26 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_auto_20200226_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-created_at',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='customuserregistration',
            options={'ordering': ('-created_at',), 'verbose_name': 'User (for selling)', 'verbose_name_plural': 'Users (for selling)'},
        ),
        migrations.RemoveField(
            model_name='customuserregistration',
            name='shop_link',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuserregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuserregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
