# Generated by Django 3.0.3 on 2020-02-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_auto_20200226_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='customuserregistration',
            options={'verbose_name': 'User (for selling)', 'verbose_name_plural': 'Users (for selling)'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customuserregistration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuserregistration',
            name='updated_at',
        ),
    ]
