# Generated by Django 3.0.3 on 2020-03-02 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_auto_20200226_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuserregistration',
            name='shop_link',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuserregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
