# Generated by Django 3.0.3 on 2020-03-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200302_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category_count',
            field=models.PositiveIntegerField(default=0, verbose_name="product's count"),
        ),
    ]
