# Generated by Django 3.0.3 on 2020-03-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200303_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryproperty',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productproperty',
            old_name='product_id',
            new_name='product',
        ),
    ]
