# Generated by Django 3.0.3 on 2020-03-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200303_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='products.Category'),
        ),
    ]
